export const songsArray = [
  { "trackName": "Chip", "mainArtist": "COMA" },
  { "trackName": "Cântă-mi povestea", "mainArtist": "COMA" },
  { "trackName": "Please Please Please Let Me Get What I Want - 2005 Remaster", "mainArtist": "Deftones" },
  { "trackName": "Call Me What You Like", "mainArtist": "Lovejoy" },
  { "trackName": "Summer Again", "mainArtist": "The Wytches" },
  { "trackName": "Sextape", "mainArtist": "Deftones" },
  { "trackName": "Vânătoarea regală", "mainArtist": "Robin and the Backstabbers" },
  { "trackName": "Aur", "mainArtist": "Toulouse Lautrec" },
  { "trackName": "Dejun Pe Iarba", "mainArtist": "Toulouse Lautrec" },
  { "trackName": "Fata in Boxeri Si in Tricoul Alb", "mainArtist": "Vama" },
  { "trackName": "505", "mainArtist": "Arctic Monkeys" },
  { "trackName": "Knee Socks", "mainArtist": "Arctic Monkeys" },
  { "trackName": "I Wanna Be Yours", "mainArtist": "Arctic Monkeys" },
  { "trackName": "we fell in love in october", "mainArtist": "girl in red" },
  { "trackName": "Inima", "mainArtist": "Sex Pula Pistol" },
  { "trackName": "Nebun De Alb", "mainArtist": "Emeric Imre" },
  { "trackName": "Rosu Aprins", "mainArtist": "Luna Amara" },
  { "trackName": "La Capăt De Linie", "mainArtist": "om la luna" },
  { "trackName": "Word Up!", "mainArtist": "Korn" },
  { "trackName": "Nu pot trăi fără tine", "mainArtist": "Cargo" },
  { "trackName": "Right Now", "mainArtist": "Korn" },
  { "trackName": "September", "mainArtist": "Earth, Wind & Fire" },
  { "trackName": "Parasite Eve", "mainArtist": "Bring Me The Horizon" },
  { "trackName": "Lonely Day", "mainArtist": "System Of A Down" },
  { "trackName": "Codru", "mainArtist": "E-An-Na" },
  { "trackName": "Izbândă şi a râvni", "mainArtist": "E-An-Na" },
  { "trackName": "Hasta siempre comandante Che Guevara", "mainArtist": "César le Groupe Temoignage" },
  { "trackName": "Perfect", "mainArtist": "Ed Sheeran" },
  { "trackName": "rose", "mainArtist": "Anna Tsuchiya" },
  { "trackName": "Preocupat cu gura ta", "mainArtist": "Smiley" },
  { "trackName": "Pic pic", "mainArtist": "Voltaj" },
  { "trackName": "Explozie solară", "mainArtist": "Bosquito" },
  { "trackName": "Total Eclipse of the Heart", "mainArtist": "Bonnie Tyler" },
  { "trackName": "THE DRIVER", "mainArtist": "Måneskin" },
  { "trackName": "OFF MY FACE", "mainArtist": "Måneskin" },
  { "trackName": "VALENTINE", "mainArtist": "Måneskin" },
  { "trackName": "Rock & Roll Queen", "mainArtist": "The Subways" }
]