export const songsArray = [
  { trackName: 'Blind - Live at CBGB', mainArtist: 'Korn' },
  { trackName: 'Freak On a Leash', mainArtist: 'Korn' },
  { trackName: 'A.D.I.D.A.S.', mainArtist: 'Korn' },
  { trackName: 'Twisted Transistor', mainArtist: 'Korn' },
  { trackName: "Y'all Want a Single", mainArtist: 'Korn' },
  { trackName: 'Shoots and Ladders', mainArtist: 'Korn' },
  { trackName: 'Clown', mainArtist: 'Korn' },
  { trackName: 'Engine No. 9', mainArtist: 'Deftones' },
  { trackName: 'Around the Fur', mainArtist: 'Deftones' },
  { trackName: 'Rotting In Vain', mainArtist: 'Korn' },
  { trackName: 'Do It So Good', mainArtist: 'WARGASM (UK)' },
  { trackName: 'Venom', mainArtist: 'WARGASM (UK)' },
  { trackName: 'Minigun', mainArtist: 'WARGASM (UK)' },
  {
    trackName: 'Bang Ya Head (feat. Fred Durst)',
    mainArtist: 'WARGASM (UK)'
  },
  { trackName: 'DANGER', mainArtist: 'South Arcade' },
  { trackName: 'HOW 2 GET AWAY WITH MURDER', mainArtist: 'South Arcade' },
  { trackName: 'Beg for Me', mainArtist: 'Korn' },
  { trackName: 'Swerve City', mainArtist: 'Deftones' },
  { trackName: 'Right Now', mainArtist: 'Korn' },
  { trackName: "You'll Never Find Me", mainArtist: 'Korn' },
  { trackName: 'Blind', mainArtist: 'Korn' },
  { trackName: 'Cold', mainArtist: 'Korn' },
  { trackName: 'Gore', mainArtist: 'Deftones' },
  { trackName: 'Prison Song', mainArtist: 'System Of A Down' },
  { trackName: 'I-E-A-I-A-I-O', mainArtist: 'System Of A Down' },
  { trackName: 'Psycho', mainArtist: 'System Of A Down' },
  { trackName: 'Coming Undone', mainArtist: 'Korn' },
  { trackName: 'Sad Statue', mainArtist: 'System Of A Down' },
  { trackName: 'Got the Life', mainArtist: 'Korn' },
  { trackName: 'Innervision', mainArtist: 'System Of A Down' },
  { trackName: 'Falling Away from Me', mainArtist: 'Korn' },
  { trackName: 'My Way', mainArtist: 'Limp Bizkit' },
  { trackName: 'Deer Dance', mainArtist: 'System Of A Down' },
  { trackName: 'Radio/Video', mainArtist: 'System Of A Down' },
  { trackName: 'Did My Time', mainArtist: 'Korn' },
  { trackName: 'Salma Hayek', mainArtist: 'WARGASM (UK)' },
  { trackName: 'Heavy Is the Crown', mainArtist: 'Linkin Park' },
  { trackName: 'The Emptiness Machine', mainArtist: 'Linkin Park' },
  { trackName: 'THE DEATH OF PEACE OF MIND', mainArtist: 'Bad Omens' },
  { trackName: 'ANYTHING > HUMAN', mainArtist: 'Bad Omens' },
  { trackName: 'Just Pretend', mainArtist: 'Bad Omens' },
  { trackName: 'V.A.N', mainArtist: 'Bad Omens' },
  { trackName: 'Back to School (Mini Maggit)', mainArtist: 'Deftones' },
  { trackName: 'Forest', mainArtist: 'System Of A Down' },
  { trackName: 'Dethrone', mainArtist: 'Bad Omens' },
  { trackName: 'Self Destructor', mainArtist: 'Chevelle' },
  { trackName: 'Word Up!', mainArtist: 'Korn' },
  { trackName: 'Tu Romanca Eu Tigan', mainArtist: 'Liviu Pustiu' },
  { trackName: 'Pustoaico cu Par Roscat', mainArtist: 'Nicolae Guta' },
  {
    trackName: 'A Different World (feat. Corey Taylor)',
    mainArtist: 'Korn'
  },
  { trackName: 'VREI', mainArtist: 'HVNDS' },
  { trackName: 'Covet', mainArtist: 'Basement' },
  { trackName: 'OWN MY MIND', mainArtist: 'Måneskin' },
  { trackName: 'TIMEZONE', mainArtist: 'Måneskin' },
  { trackName: 'IF NOT FOR YOU', mainArtist: 'Måneskin' },
  { trackName: 'CORALINE', mainArtist: 'Måneskin' },
  { trackName: 'I WANNA BE YOUR SLAVE', mainArtist: 'Måneskin' },
  { trackName: 'FOR YOUR LOVE', mainArtist: 'Måneskin' },
  { trackName: 'THE LONELIEST', mainArtist: 'Måneskin' },
  { trackName: 'Tigara, Cafea', mainArtist: 'Azur' },
  { trackName: 'M-am indragostit numai de ea', mainArtist: 'Ducu Bertzi' },
  { trackName: 'Cel mai frumos loc de pe pamant', mainArtist: 'COMA' },
  { trackName: 'Document', mainArtist: 'COMA' },
  { trackName: 'Chip', mainArtist: 'COMA' },
  { trackName: 'Cântă-mi povestea', mainArtist: 'COMA' },
  {
    trackName: 'Please Please Please Let Me Get What I Want - 2005 Remaster',
    mainArtist: 'Deftones'
  },
  { trackName: 'Call Me What You Like', mainArtist: 'Lovejoy' },
  { trackName: 'Summer Again', mainArtist: 'The Wytches' },
  { trackName: 'Sextape', mainArtist: 'Deftones' },
  {
    trackName: 'Vânătoarea regală',
    mainArtist: 'Robin and the Backstabbers'
  },
  { trackName: 'Aur', mainArtist: 'Toulouse Lautrec' },
  { trackName: 'Dejun Pe Iarba', mainArtist: 'Toulouse Lautrec' },
  { trackName: 'Fata in Boxeri Si in Tricoul Alb', mainArtist: 'Vama' },
  { trackName: '505', mainArtist: 'Arctic Monkeys' },
  { trackName: 'Knee Socks', mainArtist: 'Arctic Monkeys' },
  { trackName: 'I Wanna Be Yours', mainArtist: 'Arctic Monkeys' },
  { trackName: 'we fell in love in october', mainArtist: 'girl in red' },
  { trackName: 'Inima', mainArtist: 'Sex Pula Pistol' },
  { trackName: 'Nebun De Alb', mainArtist: 'Emeric Imre' },
  { trackName: 'Rosu Aprins', mainArtist: 'Luna Amara' },
  { trackName: 'La Capăt De Linie', mainArtist: 'om la luna' },
  { trackName: 'Word Up!', mainArtist: 'Korn' },
  { trackName: 'Nu pot trăi fără tine', mainArtist: 'Cargo' },
  { trackName: 'Right Now', mainArtist: 'Korn' },
  { trackName: 'September', mainArtist: 'Earth, Wind & Fire' },
  { trackName: 'Parasite Eve', mainArtist: 'Bring Me The Horizon' },
  { trackName: 'Lonely Day', mainArtist: 'System Of A Down' },
  { trackName: 'Codru', mainArtist: 'E-An-Na' },
  { trackName: 'Izbândă şi a râvni', mainArtist: 'E-An-Na' },
  {
    trackName: 'Hasta siempre comandante Che Guevara',
    mainArtist: 'César le Groupe Temoignage'
  },
  { trackName: 'Perfect', mainArtist: 'Ed Sheeran' },
  { trackName: 'rose', mainArtist: 'Anna Tsuchiya' },
  { trackName: 'Preocupat cu gura ta', mainArtist: 'Smiley' },
  { trackName: 'Pic pic', mainArtist: 'Voltaj' },
  { trackName: 'Explozie solară', mainArtist: 'Bosquito' },
  { trackName: 'Total Eclipse of the Heart', mainArtist: 'Bonnie Tyler' },
  { trackName: 'THE DRIVER', mainArtist: 'Måneskin' },
  { trackName: 'OFF MY FACE', mainArtist: 'Måneskin' },
  { trackName: 'VALENTINE', mainArtist: 'Måneskin' },
  { trackName: 'Rock & Roll Queen', mainArtist: 'The Subways' }
];